### ISSUE TITLE
Maximum length of the user should be 50 characters.

### ISSUE THREAD

**Issue by saikiran76** [saikiran76/Full_stack_application#2]
In the user schema of models, the user name should be of length 50 characters.

**Comment by divyanshu29jha** [comment]
@saikiran76 Please assign this to me

**Comment by divyanshu29jha** [comment]
@saikiran76 Please assign this to me
Thank you

**Comment by saikiran76** [comment]
@divyanshu29jha Glad you have resolved the issue. Have a wonderful open-source journey ahead and there is another simple issue if you want to work on.
